import init from "@rainbowatcher/toml-edit-js";
import { readFileSync } from "fs";
import { resolve } from "path";
import { describe, expect, it } from "vitest";
import { CargoLock } from "../../../src/updaters/rust/cargoLock";
import { Version } from "../../../src/version";

const fixturesPath = "./test/fixtures";

describe("CargoLock", () => {
    const releaseVersion = Version.parse("1.2.3");
    const versionsMap = new Map<string, Version>([["package", releaseVersion]]);
    const updater = new CargoLock(versionsMap);

    it("updates the content", async () => {
        await init();

        const oldCargoLock = readFileSync(resolve(fixturesPath, "./Cargo.lock"), "utf8").replace(/\r\n/g, "\n")
        const updatedCargoLock = updater.updateContent(oldCargoLock);

        await expect(updatedCargoLock).toMatchFileSnapshot("../../fixtures/Cargo-snapshot.lock")
    });

    it("only updates the version of packages present in the versions map", async () => {
        await init();

        const content = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "package-two"
version = "2.3.2"
dependencies = []

[[package]]
name = "package"
version = "0.1.0"
dependencies = []
`;

        const updatedContent = updater.updateContent(content);

        expect(updatedContent).toContain('name = "package"\nversion = "1.2.3"');
        expect(updatedContent).toContain('name = "package-two"\nversion = "2.3.2"');
    });

    it("regression: updates the correct package when the matching package is not first in the file", async () => {
        // Bug: the updater used to look up the position of a package to update within the
        // *filtered* list of matching packages, instead of its position in the full package
        // list. That mismatch caused it to edit the wrong `[[package]]` entry whenever the
        // matching package wasn't first in the lockfile.
        await init();

        const content = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "package-two"
version = "2.3.2"
dependencies = []

[[package]]
name = "package-three"
version = "3.0.0"
dependencies = []

[[package]]
name = "package"
version = "0.1.0"
dependencies = []
`;

        const updatedContent = updater.updateContent(content);

        expect(updatedContent).toContain('name = "package"\nversion = "1.2.3"');
        expect(updatedContent).toContain('name = "package-two"\nversion = "2.3.2"');
        expect(updatedContent).toContain('name = "package-three"\nversion = "3.0.0"');
    });

    it("updates multiple packages present in the versions map", async () => {
        await init();

        const multiVersionsMap = new Map<string, Version>([
            ["package-two", Version.parse("2.4.0")],
            ["package", releaseVersion],
        ]);
        const multiUpdater = new CargoLock(multiVersionsMap);

        const content = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "package-two"
version = "2.3.2"
dependencies = []

[[package]]
name = "package"
version = "0.1.0"
dependencies = []
`;

        const updatedContent = multiUpdater.updateContent(content);

        expect(updatedContent).toContain('name = "package-two"\nversion = "2.4.0"');
        expect(updatedContent).toContain('name = "package"\nversion = "1.2.3"');
    });

    it("returns the unchanged content if no package matches the versions map", async () => {
        await init();

        const content = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "unrelated-package"
version = "0.1.0"
dependencies = []
`;

        const updatedContent = updater.updateContent(content);

        expect(updatedContent).toBe(content);
    });

    it("returns an empty string if the content is undefined", async () => {
        await init();

        const updatedContent = updater.updateContent(undefined);

        expect(updatedContent).toBe("");
    });
});
